kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
  name: ghost-site
  namespace: test
  labels:
    app: ghost-site
    app.kubernetes.io/component: ghost-site
    app.kubernetes.io/instance: ghost-site
    app.kubernetes.io/name: ghost-site
    app.kubernetes.io/part-of: ghost-site
    app.openshift.io/runtime-namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost-site
  template:
    metadata:
      labels:
        app: ghost-site
        deploymentconfig: ghost-site
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
    spec:
      volumes:
        - name: ghost-site-1
          emptyDir: {}
      containers:
        - name: ghost-site
          image: ghost
          ports:
            - containerPort: 2368
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: ghost-site-1
              mountPath: /var/lib/ghost/content
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
