apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: push-htpasswd-policy
policyDefaults:
  namespace: policies
  placement:
    clusterSelectors:
      vendor: "OpenShift"
  remediationAction: enforce
policies:
  - name: push-htpasswd-policy
    manifests:
      - path: htpasswd-policy.yaml
